"""초기 시드 데이터 — 카테고리 + 대표 프로젝트 + 시즌 + 뱃지"""

import asyncio
import math
from datetime import datetime, date, timedelta

from sqlalchemy import delete, select

from app.core.database import async_session_factory, engine, Base
from app.models.category import Category
from app.models.project import Project, FoundationType, CNCFStage, AggregationPolicy
from app.models.project_source import ProjectSource, SourceType
from app.models.daily_metric import ProjectMetricDaily
from app.models.score import ProjectScoreDaily
from app.models.season import Season, SeasonStatus
from app.models.badge import Badge
from app.models.news import NewsArticle, NewsArticleProject, NewsSource


CATEGORIES = [
    ("kubernetes", "쿠버네티스", "Kubernetes", 1),
    ("container-runtime", "컨테이너 런타임", "Container Runtime", 2),
    ("service-mesh", "서비스 메시", "Service Mesh", 3),
    ("networking-cni", "네트워킹/CNI", "Networking/CNI", 4),
    ("ingress-api-gateway", "인그레스/API 게이트웨이", "Ingress/API Gateway", 5),
    ("observability", "관측성/모니터링", "Observability/Monitoring", 6),
    ("logging", "로깅", "Logging", 7),
    ("security", "보안", "Security", 8),
    ("storage", "스토리지", "Storage", 9),
    ("database", "데이터베이스", "Database", 10),
    ("messaging", "메시징/스트리밍", "Messaging/Streaming", 11),
    ("cicd", "CI/CD", "CI/CD", 12),
    ("gitops", "GitOps", "GitOps", 13),
    ("iac", "IaC", "Infrastructure as Code", 14),
    ("cloud-platform", "클라우드 플랫폼", "Cloud Platform", 15),
    ("ai-ml", "AI/ML", "AI/ML", 16),
    ("dev-tools", "개발 도구", "Developer Tools", 17),
]

HISTORY_DAYS = 30

TREND_PROFILES = {
    "kubernetes": {"trend": 0.55, "volatility": 0.45, "response_hours": 26.0},
    "prometheus": {"trend": 0.82, "volatility": 0.38, "response_hours": 22.0},
    "envoy": {"trend": 0.18, "volatility": 0.52, "response_hours": 30.0},
    "argo-cd": {"trend": 0.96, "volatility": 0.42, "response_hours": 18.0},
    "cilium": {"trend": -0.28, "volatility": 0.58, "response_hours": 40.0},
    "istio": {"trend": -0.62, "volatility": 0.50, "response_hours": 54.0},
    "grafana": {"trend": 0.44, "volatility": 0.36, "response_hours": 20.0},
    "terraform": {"trend": 0.12, "volatility": 0.41, "response_hours": 36.0},
    "docker": {"trend": -0.08, "volatility": 0.44, "response_hours": 42.0},
    "etcd": {"trend": -0.36, "volatility": 0.40, "response_hours": 46.0},
    "containerd": {"trend": 0.21, "volatility": 0.34, "response_hours": 28.0},
    "opentelemetry": {"trend": 0.63, "volatility": 0.46, "response_hours": 24.0},
    "helm": {"trend": 0.19, "volatility": 0.28, "response_hours": 22.0},
    "backstage": {"trend": 0.67, "volatility": 0.40, "response_hours": 26.0},
    "flux": {"trend": 0.38, "volatility": 0.36, "response_hours": 24.0},
    "nginx": {"trend": -0.04, "volatility": 0.30, "response_hours": 30.0},
    "kafka": {"trend": 0.24, "volatility": 0.35, "response_hours": 34.0},
    "clickhouse": {"trend": 0.49, "volatility": 0.43, "response_hours": 26.0},
    "postgresql": {"trend": 0.11, "volatility": 0.22, "response_hours": 20.0},
    "supabase": {"trend": 0.88, "volatility": 0.50, "response_hours": 18.0},
    "loki": {"trend": 0.31, "volatility": 0.33, "response_hours": 25.0},
    "jaeger": {"trend": -0.14, "volatility": 0.29, "response_hours": 28.0},
    "milvus": {"trend": 0.74, "volatility": 0.52, "response_hours": 23.0},
    "trivy": {"trend": 0.53, "volatility": 0.39, "response_hours": 21.0},
    "falco": {"trend": 0.18, "volatility": 0.31, "response_hours": 22.0},
    "kyverno": {"trend": 0.42, "volatility": 0.34, "response_hours": 20.0},
    "opentofu": {"trend": 0.86, "volatility": 0.47, "response_hours": 18.0},
    "karpenter": {"trend": 0.79, "volatility": 0.44, "response_hours": 19.0},
    "crossplane": {"trend": 0.55, "volatility": 0.39, "response_hours": 21.0},
    "cert-manager": {"trend": 0.24, "volatility": 0.30, "response_hours": 20.0},
    "harbor": {"trend": 0.27, "volatility": 0.28, "response_hours": 21.0},
    "linkerd": {"trend": 0.08, "volatility": 0.27, "response_hours": 24.0},
    "keycloak": {"trend": 0.22, "volatility": 0.31, "response_hours": 23.0},
    "minio": {"trend": 0.33, "volatility": 0.37, "response_hours": 22.0},
    "redis": {"trend": 0.09, "volatility": 0.25, "response_hours": 18.0},
    "rabbitmq": {"trend": 0.11, "volatility": 0.26, "response_hours": 24.0},
    "temporal": {"trend": 0.52, "volatility": 0.35, "response_hours": 19.0},
    "airflow": {"trend": 0.15, "volatility": 0.29, "response_hours": 25.0},
    "vector": {"trend": 0.36, "volatility": 0.31, "response_hours": 22.0},
    "victoriametrics": {"trend": 0.29, "volatility": 0.30, "response_hours": 23.0},
    "airbyte": {"trend": 0.47, "volatility": 0.38, "response_hours": 21.0},
    "dbt-core": {"trend": 0.21, "volatility": 0.27, "response_hours": 20.0},
    "ollama": {"trend": 0.98, "volatility": 0.56, "response_hours": 14.0},
    "vllm": {"trend": 0.91, "volatility": 0.53, "response_hours": 16.0},
    "kserve": {"trend": 0.58, "volatility": 0.42, "response_hours": 21.0},
    "mlflow": {"trend": 0.23, "volatility": 0.28, "response_hours": 22.0},
    "kubeflow": {"trend": 0.17, "volatility": 0.34, "response_hours": 24.0},
    "langfuse": {"trend": 0.84, "volatility": 0.51, "response_hours": 15.0},
    "open-webui": {"trend": 1.0, "volatility": 0.60, "response_hours": 12.0},
    "dagger": {"trend": 0.41, "volatility": 0.33, "response_hours": 20.0},
    "calico": {"trend": 0.26, "volatility": 0.29, "response_hours": 21.0},
    "traefik": {"trend": 0.32, "volatility": 0.31, "response_hours": 20.0},
    "kong": {"trend": 0.28, "volatility": 0.30, "response_hours": 22.0},
    "vault": {"trend": 0.34, "volatility": 0.32, "response_hours": 21.0},
    "openbao": {"trend": 0.76, "volatility": 0.45, "response_hours": 18.0},
    "zitadel": {"trend": 0.57, "volatility": 0.39, "response_hours": 19.0},
    "nats": {"trend": 0.29, "volatility": 0.28, "response_hours": 20.0},
    "pulsar": {"trend": 0.18, "volatility": 0.27, "response_hours": 24.0},
    "duckdb": {"trend": 0.88, "volatility": 0.48, "response_hours": 16.0},
    "qdrant": {"trend": 0.73, "volatility": 0.44, "response_hours": 18.0},
    "weaviate": {"trend": 0.54, "volatility": 0.40, "response_hours": 20.0},
    "elasticsearch": {"trend": 0.15, "volatility": 0.25, "response_hours": 22.0},
    "apache-doris": {"trend": 0.39, "volatility": 0.34, "response_hours": 22.0},
    "spark": {"trend": 0.11, "volatility": 0.23, "response_hours": 24.0},
    "flink": {"trend": 0.24, "volatility": 0.28, "response_hours": 23.0},
    "superset": {"trend": 0.44, "volatility": 0.33, "response_hours": 21.0},
    "metabase": {"trend": 0.36, "volatility": 0.31, "response_hours": 19.0},
    "jenkins": {"trend": -0.06, "volatility": 0.24, "response_hours": 28.0},
    "tekton": {"trend": 0.31, "volatility": 0.29, "response_hours": 21.0},
    "ansible": {"trend": 0.14, "volatility": 0.22, "response_hours": 23.0},
    "gitea": {"trend": 0.48, "volatility": 0.35, "response_hours": 19.0},
    "renovate": {"trend": 0.42, "volatility": 0.30, "response_hours": 18.0},
    "netdata": {"trend": 0.21, "volatility": 0.27, "response_hours": 20.0},
    "sentry": {"trend": 0.25, "volatility": 0.26, "response_hours": 22.0},
    "tempo": {"trend": 0.33, "volatility": 0.28, "response_hours": 20.0},
    "litellm": {"trend": 0.93, "volatility": 0.54, "response_hours": 14.0},
    "llama-index": {"trend": 0.71, "volatility": 0.42, "response_hours": 17.0},
    "haystack": {"trend": 0.41, "volatility": 0.33, "response_hours": 20.0},
    "anything-llm": {"trend": 0.86, "volatility": 0.49, "response_hours": 15.0},
    "comfyui": {"trend": 0.96, "volatility": 0.57, "response_hours": 13.0},
}

NEWS_SOURCES = [
    {
        "slug": "kubernetes-blog",
        "name": "Kubernetes Blog",
        "source_type": "rss",
        "base_url": "https://kubernetes.io",
        "feed_url": "https://kubernetes.io/feed.xml",
    },
    {
        "slug": "cncf-blog",
        "name": "CNCF Blog",
        "source_type": "rss",
        "base_url": "https://www.cncf.io",
        "feed_url": "https://www.cncf.io/feed/",
    },
    {
        "slug": "grafana-blog",
        "name": "Grafana Blog",
        "source_type": "rss",
        "base_url": "https://grafana.com",
        "feed_url": "https://grafana.com/blog/feed.xml",
    },
]

NEWS_ARTICLES = [
    {
        "source_slug": "kubernetes-blog",
        "title": "Kubernetes 릴리스 후보가 공개되며 클러스터 업그레이드 기대가 높아졌습니다",
        "url": "https://kubernetes.io/blog/2026/03/24/release-candidate",
        "summary_ko": "쿠버네티스 릴리스 후보 공개로 스케줄링, 보안 기본값, 운영 편의성 개선 포인트가 다시 주목받고 있습니다.",
        "market_impact_ko": "핵심 인프라 프로젝트의 실행력과 신뢰도 해석에 긍정적이며, 인접 GitOps·서비스 메시 프로젝트 관심도도 함께 끌어올릴 수 있습니다.",
        "published_at": datetime(2026, 3, 24, 9, 0),
        "collected_at": datetime(2026, 3, 24, 9, 30),
        "importance_score": 9.2,
        "interest_score": 8.8,
        "grade": "A",
        "projects": [("kubernetes", "primary", 0.98), ("argo-cd", "mentioned", 0.63), ("istio", "mentioned", 0.58)],
    },
    {
        "source_slug": "cncf-blog",
        "title": "Prometheus 생태계 확장과 관측성 운영 사례가 CNCF 채널에서 다시 부각됐습니다",
        "url": "https://www.cncf.io/blog/2026/03/24/prometheus-observability-update",
        "summary_ko": "프로메테우스와 그라파나 기반 운영 사례가 다시 소개되며 관측성 스택 채택 확산 기대가 커졌습니다.",
        "market_impact_ko": "관측성 카테고리의 관심도와 실행력 해석을 끌어올리는 뉴스이며, 대시보드·알림 생태계 연계 종목에도 우호적입니다.",
        "published_at": datetime(2026, 3, 24, 11, 0),
        "collected_at": datetime(2026, 3, 24, 11, 25),
        "importance_score": 8.7,
        "interest_score": 9.1,
        "grade": "A",
        "projects": [("prometheus", "primary", 0.97), ("grafana", "mentioned", 0.81)],
    },
    {
        "source_slug": "cncf-blog",
        "title": "Argo CD와 GitOps 운영 자동화 사례가 대형 팀 도입 흐름으로 이어지고 있습니다",
        "url": "https://www.cncf.io/blog/2026/03/23/argo-cd-gitops-adoption",
        "summary_ko": "Argo CD 중심의 GitOps 도입 사례가 공개되며 대규모 배포 자동화와 운영 표준화 흐름이 강화되고 있습니다.",
        "market_impact_ko": "GitOps 카테고리의 실행력과 관심도를 함께 끌어올리는 재료이며, 쿠버네티스 기반 배포 파이프라인 전반에 우호적입니다.",
        "published_at": datetime(2026, 3, 23, 16, 0),
        "collected_at": datetime(2026, 3, 23, 16, 20),
        "importance_score": 8.4,
        "interest_score": 8.6,
        "grade": "A-",
        "projects": [("argo-cd", "primary", 0.98), ("kubernetes", "mentioned", 0.69)],
    },
    {
        "source_slug": "grafana-blog",
        "title": "Grafana가 운영 비용 시각화 기능을 확장하며 데이터 팀 관심을 모으고 있습니다",
        "url": "https://grafana.com/blog/2026/03/22/cost-observability-expansion",
        "summary_ko": "Grafana의 비용 관측 기능 확장 발표로 관측성과 데이터 팀의 공통 툴셋으로서 입지가 강화됐습니다.",
        "market_impact_ko": "그라파나 자체뿐 아니라 Prometheus 연계 사용성까지 부각돼 관측성 카테고리 전반에 긍정적입니다.",
        "published_at": datetime(2026, 3, 22, 13, 0),
        "collected_at": datetime(2026, 3, 22, 13, 18),
        "importance_score": 7.8,
        "interest_score": 8.3,
        "grade": "B+",
        "projects": [("grafana", "primary", 0.96), ("prometheus", "mentioned", 0.74)],
    },
]


def _clamp(value: float, minimum: float, maximum: float) -> float:
    return max(minimum, min(maximum, value))


def _oscillation(seed: int, day_index: int, speed: float, scale: float) -> float:
    return math.sin((day_index + 1 + seed) * speed) * scale


def _build_metric(project_id: int, project_seed: dict, day: date, day_index: int) -> ProjectMetricDaily:
    profile = TREND_PROFILES[project_seed["slug"]]
    trend = profile["trend"]
    volatility = profile["volatility"]
    response_hours = profile["response_hours"]
    seed = sum(ord(char) for char in project_seed["slug"]) % 17
    progress = day_index / max(HISTORY_DAYS - 1, 1)
    momentum = trend * ((progress - 0.5) * 2.1) + _oscillation(seed, day_index, 0.72, volatility * 0.55)
    daily_star_velocity = max(1, int(project_seed["stars"] * (0.00018 + max(trend, -0.2) * 0.00008)))
    stars_total = max(
        100,
        project_seed["stars"] - (HISTORY_DAYS - 1 - day_index) * daily_star_velocity,
    )
    forks_total = max(
        10,
        project_seed["forks"] - (HISTORY_DAYS - 1 - day_index) * max(1, int(daily_star_velocity * 0.28)),
    )
    watchers_total = max(
        5,
        project_seed["watchers"] - (HISTORY_DAYS - 1 - day_index) * max(1, int(daily_star_velocity * 0.05)),
    )

    stars_delta_1d = max(2, int(project_seed["stars"] * (0.00009 + 0.0001 * (momentum + 1.1))))
    stars_delta_7d = max(stars_delta_1d * 6, int(project_seed["stars"] * (0.0012 + 0.001 * (momentum + 1.0))))
    stars_delta_30d = max(stars_delta_7d * 3, int(project_seed["stars"] * (0.004 + 0.003 * (momentum + 1.0))))

    commits_30d = max(12, int(project_seed["commits_30d"] * (1 + momentum * 0.26)))
    prs_merged_30d = max(8, int(project_seed["prs_merged_30d"] * (1 + momentum * 0.24)))
    issues_closed_30d = max(6, int(project_seed["issues_closed_30d"] * (1 + momentum * 0.22)))
    contributors_30d = max(5, int(project_seed["contributors_30d"] * (1 + momentum * 0.20)))
    releases_90d = max(1, int(round(project_seed["releases_90d"] * (1 + trend * 0.15 + progress * 0.08))))

    issue_close_ratio = _clamp(0.66 + trend * 0.09 + _oscillation(seed, day_index, 0.35, 0.05), 0.4, 0.95)
    pr_merge_ratio = _clamp(0.74 + trend * 0.07 + _oscillation(seed, day_index, 0.41, 0.04), 0.45, 0.96)
    maintainer_response = _clamp(response_hours - trend * 10 + _oscillation(seed, day_index, 0.22, 8.0), 8.0, 96.0)
    stale_issue_ratio = _clamp(0.18 - trend * 0.05 + abs(_oscillation(seed, day_index, 0.33, 0.035)), 0.03, 0.42)
    velocity_percentile = _clamp(54 + trend * 26 + _oscillation(seed, day_index, 0.52, 10.0), 20.0, 98.0)
    security_score = _clamp(72 + trend * 8 + _oscillation(seed, day_index, 0.27, 4.0), 55.0, 96.0)
    dependency_risk = _clamp(29 - trend * 6 + abs(_oscillation(seed, day_index, 0.31, 6.0)), 8.0, 48.0)

    return ProjectMetricDaily(
        project_id=project_id,
        metric_date=day,
        source_type="github",
        stars_total=stars_total,
        stars_delta_1d=stars_delta_1d,
        stars_delta_7d=stars_delta_7d,
        stars_delta_30d=stars_delta_30d,
        forks_total=forks_total,
        watchers_total=watchers_total,
        commits_1d=max(1, commits_30d // 18),
        commits_7d=max(5, commits_30d // 4),
        commits_30d=commits_30d,
        prs_opened_30d=max(prs_merged_30d + 4, int(prs_merged_30d * 1.18)),
        prs_merged_30d=prs_merged_30d,
        issues_opened_30d=max(issues_closed_30d + 3, int(issues_closed_30d * 1.12)),
        issues_closed_30d=issues_closed_30d,
        contributors_30d=contributors_30d,
        contributors_90d=max(contributors_30d + 8, int(contributors_30d * 1.45)),
        release_count_90d=releases_90d,
        issue_close_ratio=issue_close_ratio,
        pr_merge_ratio=pr_merge_ratio,
        maintainer_response_hours_p50=maintainer_response,
        stale_issue_ratio=stale_issue_ratio,
        velocity_percentile=velocity_percentile,
        security_score_raw=security_score,
        dependency_risk_score_raw=dependency_risk,
        last_commit_at=datetime.combine(day, datetime.min.time()) + timedelta(hours=10),
        last_release_at=datetime.combine(day, datetime.min.time()) - timedelta(days=max(1, 10 - int(trend * 4))),
    )

SEED_PROJECTS = [
    {
        "slug": "kubernetes",
        "name_ko": "쿠버네티스",
        "name_en": "Kubernetes",
        "desc_ko": "프로덕션 등급 컨테이너 오케스트레이션 시스템",
        "desc_en": "Production-Grade Container Orchestration",
        "repo": "https://github.com/kubernetes/kubernetes",
        "foundation": FoundationType.CNCF,
        "cncf_stage": CNCFStage.GRADUATED,
        "category": "kubernetes",
        "language": "Go",
        "stars": 112000, "forks": 39000, "watchers": 3200,
        "commits_30d": 450, "prs_merged_30d": 320, "issues_closed_30d": 280,
        "contributors_30d": 180, "releases_90d": 8,
    },
    {
        "slug": "prometheus",
        "name_ko": "프로메테우스",
        "name_en": "Prometheus",
        "desc_ko": "시스템 모니터링 및 알림 툴킷",
        "desc_en": "The Prometheus monitoring system and time series database",
        "repo": "https://github.com/prometheus/prometheus",
        "foundation": FoundationType.CNCF,
        "cncf_stage": CNCFStage.GRADUATED,
        "category": "observability",
        "language": "Go",
        "stars": 56000, "forks": 9100, "watchers": 1100,
        "commits_30d": 120, "prs_merged_30d": 85, "issues_closed_30d": 60,
        "contributors_30d": 45, "releases_90d": 3,
    },
    {
        "slug": "envoy",
        "name_ko": "엔보이",
        "name_en": "Envoy",
        "desc_ko": "클라우드 네이티브 고성능 L7 프록시",
        "desc_en": "Cloud-native high-performance edge/middle/service proxy",
        "repo": "https://github.com/envoyproxy/envoy",
        "foundation": FoundationType.CNCF,
        "cncf_stage": CNCFStage.GRADUATED,
        "category": "networking-cni",
        "language": "C++",
        "stars": 25000, "forks": 4900, "watchers": 550,
        "commits_30d": 200, "prs_merged_30d": 150, "issues_closed_30d": 90,
        "contributors_30d": 70, "releases_90d": 4,
    },
    {
        "slug": "argo-cd",
        "name_ko": "Argo CD",
        "name_en": "Argo CD",
        "desc_ko": "쿠버네티스를 위한 선언적 GitOps 지속 배포 도구",
        "desc_en": "Declarative Continuous Deployment for Kubernetes",
        "repo": "https://github.com/argoproj/argo-cd",
        "foundation": FoundationType.CNCF,
        "cncf_stage": CNCFStage.GRADUATED,
        "category": "gitops",
        "language": "Go",
        "stars": 18000, "forks": 5500, "watchers": 280,
        "commits_30d": 90, "prs_merged_30d": 65, "issues_closed_30d": 45,
        "contributors_30d": 35, "releases_90d": 2,
    },
    {
        "slug": "cilium",
        "name_ko": "실리움",
        "name_en": "Cilium",
        "desc_ko": "eBPF 기반 네트워킹, 관측성, 보안",
        "desc_en": "eBPF-based Networking, Observability, Security",
        "repo": "https://github.com/cilium/cilium",
        "foundation": FoundationType.CNCF,
        "cncf_stage": CNCFStage.GRADUATED,
        "category": "networking-cni",
        "language": "Go",
        "stars": 20000, "forks": 2900, "watchers": 350,
        "commits_30d": 150, "prs_merged_30d": 110, "issues_closed_30d": 70,
        "contributors_30d": 55, "releases_90d": 3,
    },
    {
        "slug": "istio",
        "name_ko": "이스티오",
        "name_en": "Istio",
        "desc_ko": "서비스 메시 플랫폼",
        "desc_en": "An open platform to connect, manage, and secure microservices",
        "repo": "https://github.com/istio/istio",
        "foundation": FoundationType.CNCF,
        "cncf_stage": CNCFStage.GRADUATED,
        "category": "service-mesh",
        "language": "Go",
        "stars": 36000, "forks": 7700, "watchers": 950,
        "commits_30d": 100, "prs_merged_30d": 75, "issues_closed_30d": 55,
        "contributors_30d": 40, "releases_90d": 3,
    },
    {
        "slug": "grafana",
        "name_ko": "그라파나",
        "name_en": "Grafana",
        "desc_ko": "오픈 소스 관측성 및 데이터 시각화 플랫폼",
        "desc_en": "The open and composable observability and data visualization platform",
        "repo": "https://github.com/grafana/grafana",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "observability",
        "language": "TypeScript",
        "stars": 65000, "forks": 12000, "watchers": 1400,
        "commits_30d": 350, "prs_merged_30d": 280, "issues_closed_30d": 200,
        "contributors_30d": 120, "releases_90d": 6,
    },
    {
        "slug": "terraform",
        "name_ko": "테라폼",
        "name_en": "Terraform",
        "desc_ko": "인프라를 코드로 안전하게 구축, 변경 및 버전 관리",
        "desc_en": "Terraform enables you to safely and predictably create, change, and improve infrastructure",
        "repo": "https://github.com/hashicorp/terraform",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "iac",
        "language": "Go",
        "stars": 43000, "forks": 9500, "watchers": 1100,
        "commits_30d": 80, "prs_merged_30d": 50, "issues_closed_30d": 40,
        "contributors_30d": 25, "releases_90d": 2,
    },
    {
        "slug": "docker",
        "name_ko": "도커 (Moby)",
        "name_en": "Docker (Moby)",
        "desc_ko": "컨테이너 생태계를 위한 오픈 프레임워크",
        "desc_en": "The Moby Project - a collaborative project for the container ecosystem",
        "repo": "https://github.com/moby/moby",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "container-runtime",
        "language": "Go",
        "stars": 69000, "forks": 18000, "watchers": 2900,
        "commits_30d": 60, "prs_merged_30d": 40, "issues_closed_30d": 30,
        "contributors_30d": 20, "releases_90d": 2,
    },
    {
        "slug": "etcd",
        "name_ko": "etcd",
        "name_en": "etcd",
        "desc_ko": "분산 키-값 저장소",
        "desc_en": "Distributed reliable key-value store",
        "repo": "https://github.com/etcd-io/etcd",
        "foundation": FoundationType.CNCF,
        "cncf_stage": CNCFStage.GRADUATED,
        "category": "database",
        "language": "Go",
        "stars": 48000, "forks": 9800, "watchers": 1200,
        "commits_30d": 50, "prs_merged_30d": 35, "issues_closed_30d": 25,
        "contributors_30d": 18, "releases_90d": 2,
    },
    {
        "slug": "containerd",
        "name_ko": "containerd",
        "name_en": "containerd",
        "desc_ko": "클라우드 네이티브 컨테이너 런타임",
        "desc_en": "An industry-standard container runtime",
        "repo": "https://github.com/containerd/containerd",
        "foundation": FoundationType.CNCF,
        "cncf_stage": CNCFStage.GRADUATED,
        "category": "container-runtime",
        "language": "Go",
        "stars": 18000, "forks": 3600, "watchers": 420,
        "commits_30d": 95, "prs_merged_30d": 68, "issues_closed_30d": 52,
        "contributors_30d": 30, "releases_90d": 3,
    },
    {
        "slug": "opentelemetry",
        "name_ko": "OpenTelemetry",
        "name_en": "OpenTelemetry",
        "desc_ko": "관측성 데이터 수집과 전송을 위한 개방형 표준",
        "desc_en": "An observability framework for cloud-native software",
        "repo": "https://github.com/open-telemetry/opentelemetry-collector",
        "foundation": FoundationType.CNCF,
        "cncf_stage": CNCFStage.GRADUATED,
        "category": "observability",
        "language": "Go",
        "stars": 69000, "forks": 13500, "watchers": 980,
        "commits_30d": 210, "prs_merged_30d": 155, "issues_closed_30d": 122,
        "contributors_30d": 78, "releases_90d": 5,
    },
    {
        "slug": "helm",
        "name_ko": "헬름",
        "name_en": "Helm",
        "desc_ko": "쿠버네티스 패키지 매니저",
        "desc_en": "The package manager for Kubernetes",
        "repo": "https://github.com/helm/helm",
        "foundation": FoundationType.CNCF,
        "cncf_stage": CNCFStage.GRADUATED,
        "category": "kubernetes",
        "language": "Go",
        "stars": 29000, "forks": 7200, "watchers": 670,
        "commits_30d": 72, "prs_merged_30d": 48, "issues_closed_30d": 39,
        "contributors_30d": 26, "releases_90d": 3,
    },
    {
        "slug": "backstage",
        "name_ko": "Backstage",
        "name_en": "Backstage",
        "desc_ko": "개발자 포털과 내부 플랫폼을 위한 오픈 프레임워크",
        "desc_en": "An open framework for building developer portals",
        "repo": "https://github.com/backstage/backstage",
        "foundation": FoundationType.CNCF,
        "cncf_stage": CNCFStage.INCUBATING,
        "category": "dev-tools",
        "language": "TypeScript",
        "stars": 29000, "forks": 5200, "watchers": 540,
        "commits_30d": 160, "prs_merged_30d": 124, "issues_closed_30d": 88,
        "contributors_30d": 64, "releases_90d": 4,
    },
    {
        "slug": "flux",
        "name_ko": "Flux",
        "name_en": "Flux",
        "desc_ko": "쿠버네티스용 GitOps 지속 배포 도구",
        "desc_en": "The GitOps family of continuous delivery tools",
        "repo": "https://github.com/fluxcd/flux2",
        "foundation": FoundationType.CNCF,
        "cncf_stage": CNCFStage.GRADUATED,
        "category": "gitops",
        "language": "Go",
        "stars": 7200, "forks": 1400, "watchers": 160,
        "commits_30d": 88, "prs_merged_30d": 57, "issues_closed_30d": 42,
        "contributors_30d": 24, "releases_90d": 3,
    },
    {
        "slug": "nginx",
        "name_ko": "NGINX",
        "name_en": "NGINX",
        "desc_ko": "웹 서버, 리버스 프록시, API 게이트웨이",
        "desc_en": "HTTP and reverse proxy server",
        "repo": "https://github.com/nginx/nginx",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "ingress-api-gateway",
        "language": "C",
        "stars": 27000, "forks": 6500, "watchers": 890,
        "commits_30d": 35, "prs_merged_30d": 24, "issues_closed_30d": 18,
        "contributors_30d": 12, "releases_90d": 2,
    },
    {
        "slug": "kafka",
        "name_ko": "Kafka",
        "name_en": "Kafka",
        "desc_ko": "분산 스트리밍 플랫폼",
        "desc_en": "Open-source distributed event streaming platform",
        "repo": "https://github.com/apache/kafka",
        "foundation": FoundationType.APACHE,
        "cncf_stage": None,
        "category": "messaging",
        "language": "Java",
        "stars": 32000, "forks": 14000, "watchers": 1200,
        "commits_30d": 130, "prs_merged_30d": 82, "issues_closed_30d": 60,
        "contributors_30d": 38, "releases_90d": 3,
    },
    {
        "slug": "clickhouse",
        "name_ko": "ClickHouse",
        "name_en": "ClickHouse",
        "desc_ko": "고성능 분석용 컬럼 지향 DBMS",
        "desc_en": "A fast open-source column-oriented DBMS",
        "repo": "https://github.com/ClickHouse/ClickHouse",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "database",
        "language": "C++",
        "stars": 42000, "forks": 7600, "watchers": 730,
        "commits_30d": 240, "prs_merged_30d": 175, "issues_closed_30d": 140,
        "contributors_30d": 85, "releases_90d": 5,
    },
    {
        "slug": "postgresql",
        "name_ko": "PostgreSQL",
        "name_en": "PostgreSQL",
        "desc_ko": "강력한 오픈소스 관계형 데이터베이스",
        "desc_en": "The world's most advanced open source relational database",
        "repo": "https://github.com/postgres/postgres",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "database",
        "language": "C",
        "stars": 17000, "forks": 5600, "watchers": 690,
        "commits_30d": 110, "prs_merged_30d": 64, "issues_closed_30d": 47,
        "contributors_30d": 34, "releases_90d": 2,
    },
    {
        "slug": "supabase",
        "name_ko": "Supabase",
        "name_en": "Supabase",
        "desc_ko": "오픈소스 Firebase 대안 백엔드 플랫폼",
        "desc_en": "The open source Firebase alternative",
        "repo": "https://github.com/supabase/supabase",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "cloud-platform",
        "language": "TypeScript",
        "stars": 86000, "forks": 9500, "watchers": 1100,
        "commits_30d": 260, "prs_merged_30d": 180, "issues_closed_30d": 150,
        "contributors_30d": 96, "releases_90d": 6,
    },
    {
        "slug": "loki",
        "name_ko": "Loki",
        "name_en": "Loki",
        "desc_ko": "로그 집계 시스템",
        "desc_en": "Like Prometheus, but for logs",
        "repo": "https://github.com/grafana/loki",
        "foundation": FoundationType.CNCF,
        "cncf_stage": CNCFStage.GRADUATED,
        "category": "logging",
        "language": "Go",
        "stars": 27000, "forks": 4100, "watchers": 380,
        "commits_30d": 125, "prs_merged_30d": 86, "issues_closed_30d": 67,
        "contributors_30d": 41, "releases_90d": 4,
    },
    {
        "slug": "jaeger",
        "name_ko": "Jaeger",
        "name_en": "Jaeger",
        "desc_ko": "분산 추적 플랫폼",
        "desc_en": "Distributed tracing platform",
        "repo": "https://github.com/jaegertracing/jaeger",
        "foundation": FoundationType.CNCF,
        "cncf_stage": CNCFStage.GRADUATED,
        "category": "observability",
        "language": "Go",
        "stars": 21000, "forks": 2600, "watchers": 290,
        "commits_30d": 48, "prs_merged_30d": 31, "issues_closed_30d": 22,
        "contributors_30d": 15, "releases_90d": 2,
    },
    {
        "slug": "milvus",
        "name_ko": "Milvus",
        "name_en": "Milvus",
        "desc_ko": "오픈소스 벡터 데이터베이스",
        "desc_en": "Open-source vector database for AI applications",
        "repo": "https://github.com/milvus-io/milvus",
        "foundation": FoundationType.LINUX_FOUNDATION,
        "cncf_stage": None,
        "category": "database",
        "language": "Go",
        "stars": 36000, "forks": 3100, "watchers": 340,
        "commits_30d": 170, "prs_merged_30d": 132, "issues_closed_30d": 110,
        "contributors_30d": 52, "releases_90d": 4,
    },
    {
        "slug": "trivy",
        "name_ko": "Trivy",
        "name_en": "Trivy",
        "desc_ko": "취약점과 구성 오류를 점검하는 보안 스캐너",
        "desc_en": "A comprehensive and versatile security scanner",
        "repo": "https://github.com/aquasecurity/trivy",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "security",
        "language": "Go",
        "stars": 28000, "forks": 2700, "watchers": 360,
        "commits_30d": 118, "prs_merged_30d": 84, "issues_closed_30d": 63,
        "contributors_30d": 33, "releases_90d": 4,
    },
    {
        "slug": "falco",
        "name_ko": "Falco",
        "name_en": "Falco",
        "desc_ko": "클라우드 네이티브 런타임 보안 프로젝트",
        "desc_en": "Cloud-native runtime security project",
        "repo": "https://github.com/falcosecurity/falco",
        "foundation": FoundationType.CNCF,
        "cncf_stage": CNCFStage.GRADUATED,
        "category": "security",
        "language": "C++",
        "stars": 8400, "forks": 920, "watchers": 110,
        "commits_30d": 62, "prs_merged_30d": 41, "issues_closed_30d": 29,
        "contributors_30d": 19, "releases_90d": 3,
    },
    {
        "slug": "kyverno",
        "name_ko": "Kyverno",
        "name_en": "Kyverno",
        "desc_ko": "쿠버네티스 정책 엔진",
        "desc_en": "Policy engine designed for Kubernetes",
        "repo": "https://github.com/kyverno/kyverno",
        "foundation": FoundationType.CNCF,
        "cncf_stage": CNCFStage.INCUBATING,
        "category": "security",
        "language": "Go",
        "stars": 7200, "forks": 980, "watchers": 120,
        "commits_30d": 95, "prs_merged_30d": 71, "issues_closed_30d": 49,
        "contributors_30d": 28, "releases_90d": 4,
    },
    {
        "slug": "opentofu",
        "name_ko": "OpenTofu",
        "name_en": "OpenTofu",
        "desc_ko": "Terraform에서 파생된 오픈소스 IaC 도구",
        "desc_en": "Open source infrastructure as code tool forked from Terraform",
        "repo": "https://github.com/opentofu/opentofu",
        "foundation": FoundationType.LINUX_FOUNDATION,
        "cncf_stage": None,
        "category": "iac",
        "language": "Go",
        "stars": 24000, "forks": 1800, "watchers": 260,
        "commits_30d": 140, "prs_merged_30d": 102, "issues_closed_30d": 81,
        "contributors_30d": 40, "releases_90d": 4,
    },
    {
        "slug": "karpenter",
        "name_ko": "Karpenter",
        "name_en": "Karpenter",
        "desc_ko": "쿠버네티스 자동 스케일링 프로젝트",
        "desc_en": "Kubernetes node lifecycle management",
        "repo": "https://github.com/kubernetes-sigs/karpenter",
        "foundation": FoundationType.CNCF,
        "cncf_stage": CNCFStage.SANDBOX,
        "category": "kubernetes",
        "language": "Go",
        "stars": 12000, "forks": 1800, "watchers": 170,
        "commits_30d": 130, "prs_merged_30d": 96, "issues_closed_30d": 77,
        "contributors_30d": 36, "releases_90d": 4,
    },
    {
        "slug": "crossplane",
        "name_ko": "Crossplane",
        "name_en": "Crossplane",
        "desc_ko": "클라우드 리소스를 선언적으로 관리하는 컨트롤 플레인 프레임워크",
        "desc_en": "Cloud-native control plane framework",
        "repo": "https://github.com/crossplane/crossplane",
        "foundation": FoundationType.CNCF,
        "cncf_stage": CNCFStage.INCUBATING,
        "category": "cloud-platform",
        "language": "Go",
        "stars": 9800, "forks": 940, "watchers": 105,
        "commits_30d": 102, "prs_merged_30d": 73, "issues_closed_30d": 58,
        "contributors_30d": 27, "releases_90d": 3,
    },
    {
        "slug": "cert-manager",
        "name_ko": "cert-manager",
        "name_en": "cert-manager",
        "desc_ko": "쿠버네티스 인증서 관리 자동화 도구",
        "desc_en": "Cloud native certificate management",
        "repo": "https://github.com/cert-manager/cert-manager",
        "foundation": FoundationType.CNCF,
        "cncf_stage": CNCFStage.GRADUATED,
        "category": "security",
        "language": "Go",
        "stars": 12000, "forks": 1700, "watchers": 190,
        "commits_30d": 84, "prs_merged_30d": 58, "issues_closed_30d": 45,
        "contributors_30d": 24, "releases_90d": 3,
    },
    {
        "slug": "harbor",
        "name_ko": "Harbor",
        "name_en": "Harbor",
        "desc_ko": "클라우드 네이티브 아티팩트 레지스트리",
        "desc_en": "Trusted cloud native registry project",
        "repo": "https://github.com/goharbor/harbor",
        "foundation": FoundationType.CNCF,
        "cncf_stage": CNCFStage.GRADUATED,
        "category": "security",
        "language": "Go",
        "stars": 27000, "forks": 4900, "watchers": 420,
        "commits_30d": 76, "prs_merged_30d": 52, "issues_closed_30d": 41,
        "contributors_30d": 22, "releases_90d": 3,
    },
    {
        "slug": "linkerd",
        "name_ko": "Linkerd",
        "name_en": "Linkerd",
        "desc_ko": "초경량 서비스 메시",
        "desc_en": "Ultralight service mesh for Kubernetes",
        "repo": "https://github.com/linkerd/linkerd2",
        "foundation": FoundationType.CNCF,
        "cncf_stage": CNCFStage.GRADUATED,
        "category": "service-mesh",
        "language": "Go",
        "stars": 11000, "forks": 1400, "watchers": 160,
        "commits_30d": 54, "prs_merged_30d": 35, "issues_closed_30d": 26,
        "contributors_30d": 16, "releases_90d": 2,
    },
    {
        "slug": "keycloak",
        "name_ko": "Keycloak",
        "name_en": "Keycloak",
        "desc_ko": "오픈소스 IAM과 SSO 플랫폼",
        "desc_en": "Open source identity and access management",
        "repo": "https://github.com/keycloak/keycloak",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "security",
        "language": "Java",
        "stars": 27000, "forks": 7100, "watchers": 520,
        "commits_30d": 145, "prs_merged_30d": 101, "issues_closed_30d": 84,
        "contributors_30d": 43, "releases_90d": 4,
    },
    {
        "slug": "minio",
        "name_ko": "MinIO",
        "name_en": "MinIO",
        "desc_ko": "고성능 오브젝트 스토리지",
        "desc_en": "High performance object storage",
        "repo": "https://github.com/minio/minio",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "storage",
        "language": "Go",
        "stars": 53000, "forks": 5900, "watchers": 600,
        "commits_30d": 118, "prs_merged_30d": 83, "issues_closed_30d": 70,
        "contributors_30d": 31, "releases_90d": 4,
    },
    {
        "slug": "redis",
        "name_ko": "Redis",
        "name_en": "Redis",
        "desc_ko": "인메모리 데이터 구조 저장소",
        "desc_en": "In-memory data structure store",
        "repo": "https://github.com/redis/redis",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "database",
        "language": "C",
        "stars": 70000, "forks": 24000, "watchers": 1900,
        "commits_30d": 74, "prs_merged_30d": 46, "issues_closed_30d": 35,
        "contributors_30d": 20, "releases_90d": 2,
    },
    {
        "slug": "rabbitmq",
        "name_ko": "RabbitMQ",
        "name_en": "RabbitMQ",
        "desc_ko": "오픈소스 메시지 브로커",
        "desc_en": "Open source message broker",
        "repo": "https://github.com/rabbitmq/rabbitmq-server",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "messaging",
        "language": "Erlang",
        "stars": 13000, "forks": 4200, "watchers": 380,
        "commits_30d": 62, "prs_merged_30d": 39, "issues_closed_30d": 31,
        "contributors_30d": 18, "releases_90d": 2,
    },
    {
        "slug": "temporal",
        "name_ko": "Temporal",
        "name_en": "Temporal",
        "desc_ko": "분산 워크플로 오케스트레이션 엔진",
        "desc_en": "Open source durable execution system",
        "repo": "https://github.com/temporalio/temporal",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "cicd",
        "language": "Go",
        "stars": 15000, "forks": 1200, "watchers": 170,
        "commits_30d": 110, "prs_merged_30d": 78, "issues_closed_30d": 63,
        "contributors_30d": 29, "releases_90d": 3,
    },
    {
        "slug": "airflow",
        "name_ko": "Apache Airflow",
        "name_en": "Apache Airflow",
        "desc_ko": "워크플로 스케줄링 플랫폼",
        "desc_en": "Platform to programmatically author and monitor workflows",
        "repo": "https://github.com/apache/airflow",
        "foundation": FoundationType.APACHE,
        "cncf_stage": None,
        "category": "cicd",
        "language": "Python",
        "stars": 42000, "forks": 15000, "watchers": 1300,
        "commits_30d": 125, "prs_merged_30d": 89, "issues_closed_30d": 74,
        "contributors_30d": 35, "releases_90d": 3,
    },
    {
        "slug": "vector",
        "name_ko": "Vector",
        "name_en": "Vector",
        "desc_ko": "로그와 텔레메트리 파이프라인 도구",
        "desc_en": "High-performance observability data pipeline",
        "repo": "https://github.com/vectordotdev/vector",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "logging",
        "language": "Rust",
        "stars": 19000, "forks": 1500, "watchers": 190,
        "commits_30d": 97, "prs_merged_30d": 66, "issues_closed_30d": 52,
        "contributors_30d": 26, "releases_90d": 3,
    },
    {
        "slug": "victoriametrics",
        "name_ko": "VictoriaMetrics",
        "name_en": "VictoriaMetrics",
        "desc_ko": "고성능 시계열 데이터베이스",
        "desc_en": "Fast, cost-effective monitoring solution and time series database",
        "repo": "https://github.com/VictoriaMetrics/VictoriaMetrics",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "observability",
        "language": "Go",
        "stars": 15000, "forks": 1500, "watchers": 180,
        "commits_30d": 88, "prs_merged_30d": 58, "issues_closed_30d": 44,
        "contributors_30d": 23, "releases_90d": 3,
    },
    {
        "slug": "airbyte",
        "name_ko": "Airbyte",
        "name_en": "Airbyte",
        "desc_ko": "오픈소스 데이터 통합 플랫폼",
        "desc_en": "Open-source data integration platform",
        "repo": "https://github.com/airbytehq/airbyte",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "database",
        "language": "Java",
        "stars": 18000, "forks": 4500, "watchers": 300,
        "commits_30d": 132, "prs_merged_30d": 97, "issues_closed_30d": 80,
        "contributors_30d": 36, "releases_90d": 4,
    },
    {
        "slug": "dbt-core",
        "name_ko": "dbt Core",
        "name_en": "dbt Core",
        "desc_ko": "분석 엔지니어링을 위한 변환 프레임워크",
        "desc_en": "Analytics engineering workflow tool",
        "repo": "https://github.com/dbt-labs/dbt-core",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "dev-tools",
        "language": "Python",
        "stars": 11000, "forks": 1900, "watchers": 170,
        "commits_30d": 85, "prs_merged_30d": 60, "issues_closed_30d": 47,
        "contributors_30d": 21, "releases_90d": 3,
    },
    {
        "slug": "ollama",
        "name_ko": "Ollama",
        "name_en": "Ollama",
        "desc_ko": "로컬 LLM 실행 런타임",
        "desc_en": "Get up and running with large language models locally",
        "repo": "https://github.com/ollama/ollama",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "ai-ml",
        "language": "Go",
        "stars": 130000, "forks": 11000, "watchers": 1200,
        "commits_30d": 210, "prs_merged_30d": 152, "issues_closed_30d": 133,
        "contributors_30d": 74, "releases_90d": 5,
    },
    {
        "slug": "vllm",
        "name_ko": "vLLM",
        "name_en": "vLLM",
        "desc_ko": "고성능 LLM 추론 엔진",
        "desc_en": "High-throughput and memory-efficient inference engine",
        "repo": "https://github.com/vllm-project/vllm",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "ai-ml",
        "language": "Python",
        "stars": 39000, "forks": 6200, "watchers": 430,
        "commits_30d": 205, "prs_merged_30d": 160, "issues_closed_30d": 141,
        "contributors_30d": 69, "releases_90d": 4,
    },
    {
        "slug": "kserve",
        "name_ko": "KServe",
        "name_en": "KServe",
        "desc_ko": "쿠버네티스 기반 모델 서빙 플랫폼",
        "desc_en": "Standard model inference platform on Kubernetes",
        "repo": "https://github.com/kserve/kserve",
        "foundation": FoundationType.CNCF,
        "cncf_stage": CNCFStage.SANDBOX,
        "category": "ai-ml",
        "language": "Python",
        "stars": 4600, "forks": 1600, "watchers": 90,
        "commits_30d": 82, "prs_merged_30d": 59, "issues_closed_30d": 47,
        "contributors_30d": 26, "releases_90d": 3,
    },
    {
        "slug": "mlflow",
        "name_ko": "MLflow",
        "name_en": "MLflow",
        "desc_ko": "MLOps 수명주기 관리 플랫폼",
        "desc_en": "Open source platform for the ML lifecycle",
        "repo": "https://github.com/mlflow/mlflow",
        "foundation": FoundationType.LINUX_FOUNDATION,
        "cncf_stage": None,
        "category": "ai-ml",
        "language": "Python",
        "stars": 22000, "forks": 5000, "watchers": 360,
        "commits_30d": 98, "prs_merged_30d": 70, "issues_closed_30d": 56,
        "contributors_30d": 28, "releases_90d": 3,
    },
    {
        "slug": "kubeflow",
        "name_ko": "Kubeflow",
        "name_en": "Kubeflow",
        "desc_ko": "쿠버네티스 기반 머신러닝 플랫폼",
        "desc_en": "Machine learning toolkit for Kubernetes",
        "repo": "https://github.com/kubeflow/kubeflow",
        "foundation": FoundationType.CNCF,
        "cncf_stage": CNCFStage.SANDBOX,
        "category": "ai-ml",
        "language": "Python",
        "stars": 15000, "forks": 2500, "watchers": 210,
        "commits_30d": 60, "prs_merged_30d": 39, "issues_closed_30d": 31,
        "contributors_30d": 17, "releases_90d": 2,
    },
    {
        "slug": "langfuse",
        "name_ko": "Langfuse",
        "name_en": "Langfuse",
        "desc_ko": "LLM 관측성과 프롬프트 추적 플랫폼",
        "desc_en": "Open source LLM engineering platform",
        "repo": "https://github.com/langfuse/langfuse",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "ai-ml",
        "language": "TypeScript",
        "stars": 13000, "forks": 1300, "watchers": 170,
        "commits_30d": 120, "prs_merged_30d": 91, "issues_closed_30d": 73,
        "contributors_30d": 33, "releases_90d": 4,
    },
    {
        "slug": "open-webui",
        "name_ko": "Open WebUI",
        "name_en": "Open WebUI",
        "desc_ko": "LLM 앱을 위한 오픈소스 웹 인터페이스",
        "desc_en": "User-friendly AI interface for local and hosted models",
        "repo": "https://github.com/open-webui/open-webui",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "ai-ml",
        "language": "TypeScript",
        "stars": 76000, "forks": 9300, "watchers": 830,
        "commits_30d": 195, "prs_merged_30d": 141, "issues_closed_30d": 126,
        "contributors_30d": 58, "releases_90d": 5,
    },
    {
        "slug": "dagger",
        "name_ko": "Dagger",
        "name_en": "Dagger",
        "desc_ko": "개발 자동화와 파이프라인 오케스트레이션 엔진",
        "desc_en": "Programmable CI/CD engine that runs your pipelines in containers",
        "repo": "https://github.com/dagger/dagger",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "cicd",
        "language": "Go",
        "stars": 11000, "forks": 610, "watchers": 95,
        "commits_30d": 88, "prs_merged_30d": 61, "issues_closed_30d": 46,
        "contributors_30d": 24, "releases_90d": 3,
    },
    {
        "slug": "calico",
        "name_ko": "Calico",
        "name_en": "Calico",
        "desc_ko": "쿠버네티스 네트워킹과 보안을 위한 CNI 플랫폼",
        "desc_en": "Networking and network security solution for containers and Kubernetes",
        "repo": "https://github.com/projectcalico/calico",
        "foundation": FoundationType.CNCF,
        "cncf_stage": CNCFStage.INCUBATING,
        "category": "networking-cni",
        "language": "Go",
        "stars": 6800, "forks": 1600, "watchers": 120,
        "commits_30d": 86, "prs_merged_30d": 59, "issues_closed_30d": 43,
        "contributors_30d": 24, "releases_90d": 3,
    },
    {
        "slug": "traefik",
        "name_ko": "Traefik",
        "name_en": "Traefik",
        "desc_ko": "클라우드 네이티브 리버스 프록시와 API 게이트웨이",
        "desc_en": "Cloud native application proxy",
        "repo": "https://github.com/traefik/traefik",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "ingress-api-gateway",
        "language": "Go",
        "stars": 55000, "forks": 5500, "watchers": 620,
        "commits_30d": 92, "prs_merged_30d": 64, "issues_closed_30d": 49,
        "contributors_30d": 28, "releases_90d": 3,
    },
    {
        "slug": "kong",
        "name_ko": "Kong",
        "name_en": "Kong",
        "desc_ko": "오픈소스 API 게이트웨이와 서비스 커넥티비티 플랫폼",
        "desc_en": "Cloud-native API gateway and AI gateway",
        "repo": "https://github.com/Kong/kong",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "ingress-api-gateway",
        "language": "Lua",
        "stars": 42000, "forks": 4800, "watchers": 520,
        "commits_30d": 84, "prs_merged_30d": 57, "issues_closed_30d": 45,
        "contributors_30d": 22, "releases_90d": 3,
    },
    {
        "slug": "vault",
        "name_ko": "Vault",
        "name_en": "Vault",
        "desc_ko": "시크릿과 암호화 키를 관리하는 보안 플랫폼",
        "desc_en": "A tool for secrets management, encryption as a service, and privileged access management",
        "repo": "https://github.com/hashicorp/vault",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "security",
        "language": "Go",
        "stars": 34000, "forks": 4400, "watchers": 620,
        "commits_30d": 78, "prs_merged_30d": 52, "issues_closed_30d": 40,
        "contributors_30d": 21, "releases_90d": 2,
    },
    {
        "slug": "openbao",
        "name_ko": "OpenBao",
        "name_en": "OpenBao",
        "desc_ko": "오픈 거버넌스 기반 시크릿 관리 플랫폼",
        "desc_en": "Open source secrets management for the community",
        "repo": "https://github.com/openbao/openbao",
        "foundation": FoundationType.LINUX_FOUNDATION,
        "cncf_stage": None,
        "category": "security",
        "language": "Go",
        "stars": 3100, "forks": 220, "watchers": 45,
        "commits_30d": 66, "prs_merged_30d": 48, "issues_closed_30d": 37,
        "contributors_30d": 16, "releases_90d": 3,
    },
    {
        "slug": "zitadel",
        "name_ko": "ZITADEL",
        "name_en": "ZITADEL",
        "desc_ko": "오픈소스 IAM과 인증 플랫폼",
        "desc_en": "Identity infrastructure, simplified for developers",
        "repo": "https://github.com/zitadel/zitadel",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "security",
        "language": "Go",
        "stars": 11000, "forks": 650, "watchers": 120,
        "commits_30d": 102, "prs_merged_30d": 72, "issues_closed_30d": 56,
        "contributors_30d": 27, "releases_90d": 4,
    },
    {
        "slug": "nats",
        "name_ko": "NATS",
        "name_en": "NATS",
        "desc_ko": "고성능 분산 메시징 시스템",
        "desc_en": "High-performance cloud native messaging system",
        "repo": "https://github.com/nats-io/nats-server",
        "foundation": FoundationType.CNCF,
        "cncf_stage": CNCFStage.GRADUATED,
        "category": "messaging",
        "language": "Go",
        "stars": 17000, "forks": 1500, "watchers": 190,
        "commits_30d": 79, "prs_merged_30d": 54, "issues_closed_30d": 41,
        "contributors_30d": 22, "releases_90d": 3,
    },
    {
        "slug": "pulsar",
        "name_ko": "Apache Pulsar",
        "name_en": "Apache Pulsar",
        "desc_ko": "멀티테넌트 분산 메시징과 스트리밍 플랫폼",
        "desc_en": "Cloud-native distributed messaging and streaming platform",
        "repo": "https://github.com/apache/pulsar",
        "foundation": FoundationType.APACHE,
        "cncf_stage": None,
        "category": "messaging",
        "language": "Java",
        "stars": 15000, "forks": 3900, "watchers": 240,
        "commits_30d": 88, "prs_merged_30d": 61, "issues_closed_30d": 47,
        "contributors_30d": 24, "releases_90d": 3,
    },
    {
        "slug": "duckdb",
        "name_ko": "DuckDB",
        "name_en": "DuckDB",
        "desc_ko": "분석 워크로드에 최적화된 인프로세스 OLAP 데이터베이스",
        "desc_en": "In-process analytical database system",
        "repo": "https://github.com/duckdb/duckdb",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "database",
        "language": "C++",
        "stars": 32000, "forks": 2600, "watchers": 410,
        "commits_30d": 160, "prs_merged_30d": 118, "issues_closed_30d": 95,
        "contributors_30d": 42, "releases_90d": 4,
    },
    {
        "slug": "qdrant",
        "name_ko": "Qdrant",
        "name_en": "Qdrant",
        "desc_ko": "벡터 검색과 RAG를 위한 오픈소스 벡터 데이터베이스",
        "desc_en": "Vector database and search engine for next generation AI applications",
        "repo": "https://github.com/qdrant/qdrant",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "database",
        "language": "Rust",
        "stars": 23000, "forks": 1500, "watchers": 210,
        "commits_30d": 126, "prs_merged_30d": 92, "issues_closed_30d": 74,
        "contributors_30d": 31, "releases_90d": 4,
    },
    {
        "slug": "weaviate",
        "name_ko": "Weaviate",
        "name_en": "Weaviate",
        "desc_ko": "생성형 AI 애플리케이션을 위한 오픈소스 벡터 데이터베이스",
        "desc_en": "Open-source vector database for AI applications",
        "repo": "https://github.com/weaviate/weaviate",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "database",
        "language": "Go",
        "stars": 14000, "forks": 1100, "watchers": 150,
        "commits_30d": 104, "prs_merged_30d": 73, "issues_closed_30d": 58,
        "contributors_30d": 27, "releases_90d": 3,
    },
    {
        "slug": "elasticsearch",
        "name_ko": "Elasticsearch",
        "name_en": "Elasticsearch",
        "desc_ko": "검색과 분석을 위한 분산 엔진",
        "desc_en": "Distributed, RESTful search and analytics engine",
        "repo": "https://github.com/elastic/elasticsearch",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "database",
        "language": "Java",
        "stars": 72000, "forks": 25000, "watchers": 3800,
        "commits_30d": 112, "prs_merged_30d": 74, "issues_closed_30d": 59,
        "contributors_30d": 30, "releases_90d": 3,
    },
    {
        "slug": "apache-doris",
        "name_ko": "Apache Doris",
        "name_en": "Apache Doris",
        "desc_ko": "실시간 분석을 위한 MPP 기반 오픈소스 데이터 웨어하우스",
        "desc_en": "Real-time analytical database based on MPP architecture",
        "repo": "https://github.com/apache/doris",
        "foundation": FoundationType.APACHE,
        "cncf_stage": None,
        "category": "database",
        "language": "Java",
        "stars": 15000, "forks": 4100, "watchers": 180,
        "commits_30d": 145, "prs_merged_30d": 108, "issues_closed_30d": 89,
        "contributors_30d": 38, "releases_90d": 4,
    },
    {
        "slug": "spark",
        "name_ko": "Apache Spark",
        "name_en": "Apache Spark",
        "desc_ko": "대규모 데이터 처리를 위한 분산 분석 엔진",
        "desc_en": "Unified engine for large-scale data analytics",
        "repo": "https://github.com/apache/spark",
        "foundation": FoundationType.APACHE,
        "cncf_stage": None,
        "category": "database",
        "language": "Scala",
        "stars": 42000, "forks": 29000, "watchers": 2200,
        "commits_30d": 94, "prs_merged_30d": 63, "issues_closed_30d": 49,
        "contributors_30d": 25, "releases_90d": 2,
    },
    {
        "slug": "flink",
        "name_ko": "Apache Flink",
        "name_en": "Apache Flink",
        "desc_ko": "스트림과 배치 데이터를 위한 통합 처리 엔진",
        "desc_en": "Stream processing framework for distributed, high-performing data-streaming applications",
        "repo": "https://github.com/apache/flink",
        "foundation": FoundationType.APACHE,
        "cncf_stage": None,
        "category": "messaging",
        "language": "Java",
        "stars": 26000, "forks": 14000, "watchers": 920,
        "commits_30d": 89, "prs_merged_30d": 61, "issues_closed_30d": 47,
        "contributors_30d": 24, "releases_90d": 2,
    },
    {
        "slug": "superset",
        "name_ko": "Apache Superset",
        "name_en": "Apache Superset",
        "desc_ko": "오픈소스 데이터 탐색과 시각화 플랫폼",
        "desc_en": "Modern data exploration and visualization platform",
        "repo": "https://github.com/apache/superset",
        "foundation": FoundationType.APACHE,
        "cncf_stage": None,
        "category": "dev-tools",
        "language": "TypeScript",
        "stars": 73000, "forks": 15000, "watchers": 1200,
        "commits_30d": 134, "prs_merged_30d": 95, "issues_closed_30d": 78,
        "contributors_30d": 35, "releases_90d": 3,
    },
    {
        "slug": "metabase",
        "name_ko": "Metabase",
        "name_en": "Metabase",
        "desc_ko": "비개발자도 쉽게 쓰는 오픈소스 BI 도구",
        "desc_en": "The simplest, fastest way to get business intelligence and analytics to everyone",
        "repo": "https://github.com/metabase/metabase",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "dev-tools",
        "language": "Clojure",
        "stars": 42000, "forks": 5900, "watchers": 650,
        "commits_30d": 102, "prs_merged_30d": 68, "issues_closed_30d": 53,
        "contributors_30d": 26, "releases_90d": 3,
    },
    {
        "slug": "jenkins",
        "name_ko": "Jenkins",
        "name_en": "Jenkins",
        "desc_ko": "가장 널리 쓰이는 오픈소스 자동화 서버",
        "desc_en": "Leading open source automation server",
        "repo": "https://github.com/jenkinsci/jenkins",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "cicd",
        "language": "Java",
        "stars": 25000, "forks": 9100, "watchers": 920,
        "commits_30d": 61, "prs_merged_30d": 39, "issues_closed_30d": 30,
        "contributors_30d": 17, "releases_90d": 2,
    },
    {
        "slug": "tekton",
        "name_ko": "Tekton",
        "name_en": "Tekton",
        "desc_ko": "쿠버네티스 네이티브 CI/CD 프레임워크",
        "desc_en": "Cloud-native CI/CD for Kubernetes",
        "repo": "https://github.com/tektoncd/pipeline",
        "foundation": FoundationType.CNCF,
        "cncf_stage": CNCFStage.GRADUATED,
        "category": "cicd",
        "language": "Go",
        "stars": 10000, "forks": 2100, "watchers": 150,
        "commits_30d": 77, "prs_merged_30d": 55, "issues_closed_30d": 41,
        "contributors_30d": 22, "releases_90d": 3,
    },
    {
        "slug": "ansible",
        "name_ko": "Ansible",
        "name_en": "Ansible",
        "desc_ko": "에이전트리스 구성 관리와 자동화 도구",
        "desc_en": "Agentless IT automation platform",
        "repo": "https://github.com/ansible/ansible",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "iac",
        "language": "Python",
        "stars": 66000, "forks": 24000, "watchers": 1900,
        "commits_30d": 83, "prs_merged_30d": 54, "issues_closed_30d": 42,
        "contributors_30d": 23, "releases_90d": 2,
    },
    {
        "slug": "gitea",
        "name_ko": "Gitea",
        "name_en": "Gitea",
        "desc_ko": "가벼운 셀프호스팅 Git 서비스",
        "desc_en": "Lightweight code hosting solution written in Go",
        "repo": "https://github.com/go-gitea/gitea",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "dev-tools",
        "language": "Go",
        "stars": 52000, "forks": 6100, "watchers": 590,
        "commits_30d": 122, "prs_merged_30d": 86, "issues_closed_30d": 71,
        "contributors_30d": 34, "releases_90d": 4,
    },
    {
        "slug": "renovate",
        "name_ko": "Renovate",
        "name_en": "Renovate",
        "desc_ko": "의존성 업데이트 자동화 봇",
        "desc_en": "Automated dependency updates",
        "repo": "https://github.com/renovatebot/renovate",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "dev-tools",
        "language": "TypeScript",
        "stars": 19000, "forks": 2600, "watchers": 240,
        "commits_30d": 168, "prs_merged_30d": 131, "issues_closed_30d": 109,
        "contributors_30d": 47, "releases_90d": 4,
    },
    {
        "slug": "netdata",
        "name_ko": "Netdata",
        "name_en": "Netdata",
        "desc_ko": "실시간 성능 모니터링과 트러블슈팅 플랫폼",
        "desc_en": "Real-time performance monitoring",
        "repo": "https://github.com/netdata/netdata",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "observability",
        "language": "C",
        "stars": 75000, "forks": 6200, "watchers": 980,
        "commits_30d": 74, "prs_merged_30d": 51, "issues_closed_30d": 39,
        "contributors_30d": 20, "releases_90d": 3,
    },
    {
        "slug": "sentry",
        "name_ko": "Sentry",
        "name_en": "Sentry",
        "desc_ko": "에러 추적과 애플리케이션 모니터링 플랫폼",
        "desc_en": "Developer-first error tracking and performance monitoring",
        "repo": "https://github.com/getsentry/sentry",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "observability",
        "language": "Python",
        "stars": 42000, "forks": 5200, "watchers": 690,
        "commits_30d": 108, "prs_merged_30d": 76, "issues_closed_30d": 60,
        "contributors_30d": 29, "releases_90d": 3,
    },
    {
        "slug": "tempo",
        "name_ko": "Tempo",
        "name_en": "Tempo",
        "desc_ko": "고비용 샘플링 없이 추적을 저장하는 분산 트레이싱 백엔드",
        "desc_en": "High-scale distributed tracing backend",
        "repo": "https://github.com/grafana/tempo",
        "foundation": FoundationType.CNCF,
        "cncf_stage": CNCFStage.INCUBATING,
        "category": "observability",
        "language": "Go",
        "stars": 5000, "forks": 540, "watchers": 70,
        "commits_30d": 81, "prs_merged_30d": 57, "issues_closed_30d": 46,
        "contributors_30d": 22, "releases_90d": 3,
    },
    {
        "slug": "litellm",
        "name_ko": "LiteLLM",
        "name_en": "LiteLLM",
        "desc_ko": "다양한 LLM 제공자를 단일 인터페이스로 연결하는 게이트웨이",
        "desc_en": "Python SDK and proxy server to call 100+ LLM APIs in OpenAI format",
        "repo": "https://github.com/BerriAI/litellm",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "ai-ml",
        "language": "Python",
        "stars": 22000, "forks": 2800, "watchers": 260,
        "commits_30d": 182, "prs_merged_30d": 134, "issues_closed_30d": 116,
        "contributors_30d": 49, "releases_90d": 5,
    },
    {
        "slug": "llama-index",
        "name_ko": "LlamaIndex",
        "name_en": "LlamaIndex",
        "desc_ko": "RAG와 에이전트 앱을 위한 데이터 프레임워크",
        "desc_en": "Data framework for LLM applications",
        "repo": "https://github.com/run-llama/llama_index",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "ai-ml",
        "language": "Python",
        "stars": 43000, "forks": 6200, "watchers": 520,
        "commits_30d": 146, "prs_merged_30d": 104, "issues_closed_30d": 83,
        "contributors_30d": 39, "releases_90d": 4,
    },
    {
        "slug": "haystack",
        "name_ko": "Haystack",
        "name_en": "Haystack",
        "desc_ko": "LLM과 검색 기반 애플리케이션 구축 프레임워크",
        "desc_en": "Open-source LLM orchestration framework",
        "repo": "https://github.com/deepset-ai/haystack",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "ai-ml",
        "language": "Python",
        "stars": 19000, "forks": 2400, "watchers": 210,
        "commits_30d": 93, "prs_merged_30d": 67, "issues_closed_30d": 53,
        "contributors_30d": 24, "releases_90d": 3,
    },
    {
        "slug": "anything-llm",
        "name_ko": "AnythingLLM",
        "name_en": "AnythingLLM",
        "desc_ko": "문서 기반 LLM 워크스페이스와 에이전트 플랫폼",
        "desc_en": "Open-source all-in-one AI app for building private ChatGPT",
        "repo": "https://github.com/Mintplex-Labs/anything-llm",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "ai-ml",
        "language": "TypeScript",
        "stars": 47000, "forks": 4700, "watchers": 420,
        "commits_30d": 154, "prs_merged_30d": 109, "issues_closed_30d": 94,
        "contributors_30d": 41, "releases_90d": 4,
    },
    {
        "slug": "comfyui",
        "name_ko": "ComfyUI",
        "name_en": "ComfyUI",
        "desc_ko": "노드 기반 생성형 AI 워크플로 UI",
        "desc_en": "Powerful and modular diffusion model GUI and backend",
        "repo": "https://github.com/comfyanonymous/ComfyUI",
        "foundation": FoundationType.INDEPENDENT,
        "cncf_stage": None,
        "category": "ai-ml",
        "language": "Python",
        "stars": 74000, "forks": 8200, "watchers": 670,
        "commits_30d": 174, "prs_merged_30d": 121, "issues_closed_30d": 108,
        "contributors_30d": 46, "releases_90d": 4,
    },
]


async def seed():
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async with async_session_factory() as session:
        # 카테고리
        existing = (await session.execute(select(Category))).scalars().all()
        if not existing:
            for slug, name_ko, name_en, order in CATEGORIES:
                session.add(Category(slug=slug, name_ko=name_ko, name_en=name_en, sort_order=order))
            await session.flush()

        cat_map = {}
        cats = (await session.execute(select(Category))).scalars().all()
        for c in cats:
            cat_map[c.slug] = c.id

        # 프로젝트
        existing_projects = (await session.execute(select(Project))).scalars().all()
        existing_project_slugs = {project.slug for project in existing_projects}
        today = date.today()
        for p in SEED_PROJECTS:
            if p["slug"] in existing_project_slugs:
                continue
            project = Project(
                slug=p["slug"],
                display_name_ko=p["name_ko"],
                display_name_en=p["name_en"],
                short_description_ko=p["desc_ko"],
                short_description_en=p["desc_en"],
                primary_repo_url=p["repo"],
                foundation_type=p["foundation"],
                cncf_stage=p["cncf_stage"],
                category_id=cat_map.get(p["category"]),
                primary_language=p["language"],
                aggregation_policy=AggregationPolicy.SINGLE_REPO,
            )
            session.add(project)
            await session.flush()

            session.add(ProjectSource(
                project_id=project.id,
                source_type=SourceType.GITHUB,
                external_id=p["repo"].split("github.com/")[1],
                external_url=p["repo"],
                is_primary=True,
            ))

        await session.commit()
        projects = (await session.execute(select(Project))).scalars().all()
        project_map = {project.slug: project for project in projects}
        project_by_id = {project.id: project for project in projects}

        metric_rows = (await session.execute(select(ProjectMetricDaily.id))).scalars().all()
        score_rows = (await session.execute(select(ProjectScoreDaily.id))).scalars().all()
        desired_rows = len(SEED_PROJECTS) * HISTORY_DAYS
        if len(metric_rows) != desired_rows or len(score_rows) != desired_rows:
            await session.execute(delete(ProjectScoreDaily))
            await session.execute(delete(ProjectMetricDaily))
            await session.flush()

            from app.scoring.engine import score_project

            scores_by_day: dict[date, list[ProjectScoreDaily]] = {}
            for day_index, day in enumerate(
                [today - timedelta(days=offset) for offset in range(HISTORY_DAYS - 1, -1, -1)]
            ):
                day_metrics: list[ProjectMetricDaily] = []
                for project_seed in SEED_PROJECTS:
                    project = project_map[project_seed["slug"]]
                    metric = _build_metric(project.id, project_seed, day, day_index)
                    day_metrics.append(metric)
                    session.add(metric)

                day_scores: list[ProjectScoreDaily] = []
                for metric in day_metrics:
                    peers = [peer for peer in day_metrics if peer.project_id != metric.project_id]
                    score_result = score_project(metric, peers)
                    score = ProjectScoreDaily(
                        project_id=metric.project_id,
                        score_date=day,
                        attention_score=score_result.attention,
                        execution_score=score_result.execution,
                        health_score=score_result.health,
                        trust_score=score_result.trust,
                        total_score=score_result.total,
                        scoring_version="v1.0",
                    )
                    day_scores.append(score)
                    session.add(score)
                scores_by_day[day] = day_scores

            ordered_days = sorted(scores_by_day.keys())
            previous_by_project: dict[int, ProjectScoreDaily] = {}
            for day in ordered_days:
                day_scores = scores_by_day[day]
                day_scores.sort(key=lambda item: item.total_score, reverse=True)
                for rank, score in enumerate(day_scores, 1):
                    score.rank_global = rank

                cncf_scores = [
                    score for score in day_scores
                    if project_by_id[score.project_id].foundation_type == FoundationType.CNCF
                ]
                for rank, score in enumerate(cncf_scores, 1):
                    score.rank_cncf = rank

                category_groups: dict[int | None, list[ProjectScoreDaily]] = {}
                for score in day_scores:
                    project = project_by_id[score.project_id]
                    category_groups.setdefault(project.category_id, []).append(score)
                for category_scores in category_groups.values():
                    for rank, score in enumerate(category_scores, 1):
                        score.rank_category = rank

                rising_candidates: list[tuple[float, ProjectScoreDaily]] = []
                for score in day_scores:
                    previous = previous_by_project.get(score.project_id)
                    if previous:
                        rising_candidates.append((score.total_score - previous.total_score, score))
                    previous_by_project[score.project_id] = score

                for rank, (_, score) in enumerate(
                    sorted(rising_candidates, key=lambda item: item[0], reverse=True),
                    1,
                ):
                    score.rising_rank = rank

            await session.commit()

        # 시즌 생성 (§20.3)
        existing_seasons = (await session.execute(select(Season))).scalars().all()
        if not existing_seasons:
            season = Season(
                name="시즌 1",
                slug="season-1",
                start_date=today,
                end_date=today + timedelta(days=90),
                status=SeasonStatus.ACTIVE,
                is_current=True,
                initial_points=10000,
            )
            session.add(season)
            await session.flush()

        # 뱃지 시드 (§20.8)
        existing_badges = (await session.execute(select(Badge))).scalars().all()
        existing_badge_slugs = {badge.slug for badge in existing_badges}
        badge_seeds = [
            ("season_champion", "시즌 챔피언", "Season Champion", "시즌 최종 1위를 차지한 예측가", "Top predictor of the season", "🏆", "legendary"),
            ("season_top10", "상위 10 예측가", "Season Top 10", "시즌 최종 TOP 10 진입", "Finished in season top 10", "🥇", "epic"),
            ("accuracy_excellent", "정확도 우수", "Accuracy Master", "적중률 70% 이상 달성", "Achieved 70%+ accuracy", "🎯", "rare"),
            ("undervalue_hunter", "저평가 헌터", "Undervalue Hunter", "저평가된 프로젝트를 다수 적중", "Correctly predicted multiple undervalued projects", "🔍", "epic"),
            ("contrarian_hit", "역발상 적중자", "Contrarian Hit", "대세와 반대 포지션으로 적중 성공", "Successfully went against the majority", "🔄", "rare"),
            ("early_signal", "얼리 시그널", "Early Signal", "주목받기 전 프로젝트를 조기 포착", "Spotted projects before they gained attention", "⚡", "epic"),
            ("streak_master", "연속 적중왕", "Streak Master", "10연속 적중 달성", "Achieved 10 consecutive hits", "🔥", "rare"),
            ("first_prediction", "첫 예측", "First Prediction", "첫 번째 예측 완료", "Made the first prediction", "🌱", "common"),
            ("first_comment", "첫 댓글", "First Comment", "종목 커뮤니티에 첫 댓글을 남김", "Left the first market community comment", "🗣️", "common"),
            ("first_portfolio", "첫 포트폴리오", "First Portfolio", "첫 종목을 담아 포트폴리오를 구성", "Built the first portfolio position", "📦", "common"),
            ("hot_take", "핫테이커", "Hot Take", "추천을 많이 받은 댓글 작성", "Posted a widely recommended market take", "🔥", "rare"),
            ("thread_maker", "스레드 메이커", "Thread Maker", "답글이 이어지는 토론 스레드 생성", "Started a threaded market discussion", "🧵", "rare"),
            ("research_curator", "리서치 큐레이터", "Research Curator", "출처를 포함한 분석 댓글을 꾸준히 작성", "Regularly posts source-backed research comments", "📚", "epic"),
            ("bridge_builder", "브릿지 빌더", "Bridge Builder", "상반된 의견 사이를 연결하는 토론 형성", "Connects opposing viewpoints into useful discussion", "🌉", "epic"),
            ("community_anchor", "커뮤니티 앵커", "Community Anchor", "종목 커뮤니티의 핵심 토론자로 자리잡음", "Became a core discussion leader in project communities", "📣", "legendary"),
            ("momentum_surfer", "모멘텀 서퍼", "Momentum Surfer", "급등 흐름을 빠르게 포착", "Caught momentum moves early", "🚀", "rare"),
            ("rotation_reader", "로테이션 리더", "Rotation Reader", "카테고리 순환매를 선제적으로 파악", "Read category rotation ahead of the crowd", "🌊", "epic"),
            ("knife_catcher", "칼날 줍는 자", "Knife Catcher", "급락 뒤 반등 구간을 정확히 포착", "Captured rebounds after steep drawdowns", "🧊", "epic"),
            ("signal_sniper", "시그널 스나이퍼", "Signal Sniper", "짧은 순간의 핵심 신호를 놓치지 않음", "Never misses a decisive short-term signal", "🦅", "legendary"),
            ("kubernetes_ranger", "쿠버네티스 레인저", "Kubernetes Ranger", "쿠버네티스 생태계를 깊게 추적", "Tracks the Kubernetes ecosystem deeply", "☸️", "rare"),
            ("observability_watcher", "옵저버빌리티 와처", "Observability Watcher", "관측성 생태계 움직임을 지속적으로 분석", "Continuously analyzes observability market moves", "📡", "rare"),
            ("security_sentinel", "보안 센티넬", "Security Sentinel", "보안 카테고리의 리스크와 반등을 읽음", "Reads risk and recovery in security names", "🛡️", "rare"),
            ("platform_nomad", "플랫폼 노마드", "Platform Nomad", "여러 카테고리를 넘나드는 넓은 시야 보유", "Demonstrates broad range across platform categories", "🛰️", "epic"),
            ("full_season_finisher", "풀 시즌 완주", "Full Season Finisher", "시즌 내내 꾸준히 참여", "Stayed active for an entire season", "🏁", "rare"),
            ("podium_finisher", "포디움 피니셔", "Podium Finisher", "시즌 최종 TOP 3 진입", "Finished the season on the podium", "🥈", "epic"),
            ("back_to_back", "백투백", "Back to Back", "연속 시즌 상위권 진입", "Reached the top tier in back-to-back seasons", "🔁", "legendary"),
            ("signal_oracle", "시그널 오라클", "Signal Oracle", "다른 이들보다 먼저 핵심 신호를 해석", "Interprets the most important signals ahead of others", "🔮", "legendary"),
            ("black_swan_hunter", "블랙스완 헌터", "Black Swan Hunter", "예상 밖의 급변 구간을 맞춤", "Correctly called unexpected market events", "🦢", "legendary"),
            ("open_source_quant", "오픈소스 퀀트", "Open Source Quant", "정량과 정성을 함께 읽는 복합형 분석가", "Balances quantitative and qualitative market reads", "📐", "legendary"),
        ]
        for slug, name_ko, name_en, desc_ko, desc_en, icon, rarity in badge_seeds:
            if slug in existing_badge_slugs:
                continue
            session.add(Badge(
                slug=slug, name_ko=name_ko, name_en=name_en,
                description_ko=desc_ko, description_en=desc_en,
                icon=icon, badge_type=slug, rarity=rarity,
            ))

        existing_news_sources = (await session.execute(select(NewsSource))).scalars().all()
        if not existing_news_sources:
            for source in NEWS_SOURCES:
                session.add(
                    NewsSource(
                        slug=source["slug"],
                        name=source["name"],
                        source_type=source["source_type"],
                        base_url=source["base_url"],
                        feed_url=source["feed_url"],
                    )
                )
            await session.flush()

        existing_news_articles = (await session.execute(select(NewsArticle.id))).scalars().all()
        if not existing_news_articles:
            source_map = {
                source.slug: source
                for source in (await session.execute(select(NewsSource))).scalars().all()
            }
            for article_seed in NEWS_ARTICLES:
                final_score = round(
                    (article_seed["importance_score"] * 0.6 + article_seed["interest_score"] * 0.4) * 10,
                    2,
                )
                article = NewsArticle(
                    source_id=source_map[article_seed["source_slug"]].id,
                    source_url=article_seed["url"],
                    canonical_url=article_seed["url"],
                    title=article_seed["title"],
                    summary_ko=article_seed["summary_ko"],
                    market_impact_ko=article_seed["market_impact_ko"],
                    published_at=article_seed["published_at"],
                    collected_at=article_seed["collected_at"],
                    importance_score=article_seed["importance_score"],
                    interest_score=article_seed["interest_score"],
                    final_score=final_score,
                    grade=article_seed["grade"],
                    status="processed",
                    raw_meta={
                        "seed": True,
                        "origin": "krss-inspired",
                        "project_slugs": [slug for slug, _, _ in article_seed["projects"]],
                    },
                )
                session.add(article)
                await session.flush()
                for project_slug, relation_type, confidence in article_seed["projects"]:
                    project = project_map.get(project_slug)
                    if not project:
                        continue
                    session.add(
                        NewsArticleProject(
                            article_id=article.id,
                            project_id=project.id,
                            relation_type=relation_type,
                            confidence=confidence,
                        )
                    )

        await session.commit()

        badge_count = len((await session.execute(select(Badge.id))).scalars().all())

    print(
        f"시드 데이터 삽입 완료: 카테고리 {len(CATEGORIES)}개, 프로젝트 {len(SEED_PROJECTS)}개, "
        f"시즌 1개, 뱃지 {badge_count}개, 뉴스 {len(NEWS_ARTICLES)}개"
    )


if __name__ == "__main__":
    asyncio.run(seed())
